#!/bin/bash
# vi:ft=sh
# Adopted from https://github.com/mathiasbynens/dotfiles/blob/7d43ff6/.osx
set -e

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 0

# Enable full keyboard access for all controls (e.g. Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Press Tab to highlight each item on a web page
defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

# Set Safari’s home page to `about:blank` for faster loading
defaults write com.apple.Safari HomePage -string "about:blank"
# Disable site favorites when focusing Safari’s URL bar
defaults write com.apple.Safari ShowFavoritesUnderSmartSearchField -bool false
# Disable preloading top hit in the background
defaults write com.apple.Safari PreloadTopHit -bool false
# Disable Quick Website Search
defaults write com.apple.Safari WebsiteSpecificSearchEnabled -bool false
# Stop Safari from offering to store passwords and credit card data
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoFillCreditCardData -bool false

# ?? Doesn't seem to work in El Capitan ??
# Use plain text mode for new TextEdit documents
# defaults write com.apple.TextEdit RichText -int 0
# Open and save files as UTF-8 in TextEdit
# defaults write com.apple.TextEdit PlainTextEncoding -int 4
# defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

# ?? Seems to reflect in Trackpad settings, but not take effect ??
# Trackpad: enable tap to click for this user and for the login screen
# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
# defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
# defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
# Follow the keyboard focus while zoomed in
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

# Configure iTerm2 to read preferences from Dropbox
defaults write com.googlecode.iterm2 PrefsCustomFolder ~/Dropbox

exit 0
# ?? Doesn't seem to work in El Capitan ??
# Remap Caps Lock to Control for all attached keyboards
ioreg -n IOHIDKeyboard -r | awk '
  /"VendorID"/ { vid=$(NF) }
  /"ProductID"/ { print vid "-" $(NF) }
' | {
  while read keyboard; do
    if ! defaults -currentHost read -g "com.apple.keyboard.modifiermapping.${keyboard}-0" 2>/dev/null | grep -q 'Dst = 2'; then
      defaults -currentHost write -g "com.apple.keyboard.modifiermapping.${keyboard}-0" -array \
        "<dict><key>HIDKeyboardModifierMappingDst</key><integer>2</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict>"
    fi
  done
}
