#!/bin/sh
set -e

tagfile="${GIT_DIR:-.git}/tags.$$"
trap "rm -f $tagfile" EXIT

if [ -x script/ctags ]; then
  script/ctags -f "$tagfile"
else
  ctags --tag-relative -Rf "$tagfile" --exclude=.git --languages=-javascript,sql
fi

mv "$tagfile" "${tagfile%.$$}"
