#!/usr/bin/env bash
set -e

cd "${0%/*}"/..

for file in "$PWD"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  [[ "readme script vscode" =~ $name ]] && continue
  [ -e "${HOME}/${dotname}" ] && continue
  git --git-dir "${file}/.git" rev-parse --git-dir &>/dev/null && continue

  ln -sfnv ${file#$HOME/} "${HOME}/${dotname}"
done

VSCODE_USER_DIR=~/Library/Application\ Support/Code/User
mkdir -p "$VSCODE_USER_DIR"
for file in "$PWD/vscode/"*; do
  name="$(basename "$file")"
  [ -e "$VSCODE_USER_DIR/$name" ] || ln -sfnv "$file" "$VSCODE_USER_DIR/$name"
done

~/.osx
