#!/usr/bin/env bash
set -e

cd "${0%/*}"/..

type -p brew >/dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

brew cask install google-chrome slack iterm2 tmux go

./osx

echo
echo "Done! Run $PWD/script/boostrap for full setup."
